package com.example.mrrodriguez.trianadvisor.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.example.mrrodriguez.trianadvisor.greendao.Comentario;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMENTARIO".
*/
public class ComentarioDao extends AbstractDao<Comentario, Long> {

    public static final String TABLENAME = "COMENTARIO";

    /**
     * Properties of entity Comentario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property Cuerpo_comentario = new Property(2, String.class, "cuerpo_comentario", false, "CUERPO_COMENTARIO");
        public final static Property Fecha = new Property(3, String.class, "fecha", false, "FECHA");
        public final static Property UpdatedAt = new Property(4, String.class, "updatedAt", false, "UPDATED_AT");
        public final static Property UsuarioId_c = new Property(5, Long.class, "usuarioId_c", false, "USUARIO_ID_C");
        public final static Property ComentarioId_c = new Property(6, Long.class, "comentarioId_c", false, "COMENTARIO_ID_C");
    };

    private DaoSession daoSession;

    private Query<Comentario> comentario_Comentarios_sitioQuery;
    private Query<Comentario> usuario_Comentario_usuarioQuery;

    public ComentarioDao(DaoConfig config) {
        super(config);
    }
    
    public ComentarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMENTARIO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"CUERPO_COMENTARIO\" TEXT," + // 2: cuerpo_comentario
                "\"FECHA\" TEXT," + // 3: fecha
                "\"UPDATED_AT\" TEXT," + // 4: updatedAt
                "\"USUARIO_ID_C\" INTEGER," + // 5: usuarioId_c
                "\"COMENTARIO_ID_C\" INTEGER);"); // 6: comentarioId_c
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMENTARIO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Comentario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String cuerpo_comentario = entity.getCuerpo_comentario();
        if (cuerpo_comentario != null) {
            stmt.bindString(3, cuerpo_comentario);
        }
 
        String fecha = entity.getFecha();
        if (fecha != null) {
            stmt.bindString(4, fecha);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(5, updatedAt);
        }
 
        Long usuarioId_c = entity.getUsuarioId_c();
        if (usuarioId_c != null) {
            stmt.bindLong(6, usuarioId_c);
        }
 
        Long comentarioId_c = entity.getComentarioId_c();
        if (comentarioId_c != null) {
            stmt.bindLong(7, comentarioId_c);
        }
    }

    @Override
    protected void attachEntity(Comentario entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Comentario readEntity(Cursor cursor, int offset) {
        Comentario entity = new Comentario( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cuerpo_comentario
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fecha
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // updatedAt
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // usuarioId_c
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // comentarioId_c
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Comentario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCuerpo_comentario(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFecha(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUpdatedAt(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUsuarioId_c(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setComentarioId_c(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Comentario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Comentario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Comentarios_sitio" to-many relationship of Comentario. */
    public List<Comentario> _queryComentario_Comentarios_sitio(Long usuarioId_c) {
        synchronized (this) {
            if (comentario_Comentarios_sitioQuery == null) {
                QueryBuilder<Comentario> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UsuarioId_c.eq(null));
                comentario_Comentarios_sitioQuery = queryBuilder.build();
            }
        }
        Query<Comentario> query = comentario_Comentarios_sitioQuery.forCurrentThread();
        query.setParameter(0, usuarioId_c);
        return query.list();
    }

    /** Internal query to resolve the "Comentario_usuario" to-many relationship of Usuario. */
    public List<Comentario> _queryUsuario_Comentario_usuario(Long comentarioId_c) {
        synchronized (this) {
            if (usuario_Comentario_usuarioQuery == null) {
                QueryBuilder<Comentario> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ComentarioId_c.eq(null));
                usuario_Comentario_usuarioQuery = queryBuilder.build();
            }
        }
        Query<Comentario> query = usuario_Comentario_usuarioQuery.forCurrentThread();
        query.setParameter(0, comentarioId_c);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUsuarioDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getSitioDao().getAllColumns());
            builder.append(" FROM COMENTARIO T");
            builder.append(" LEFT JOIN USUARIO T0 ON T.\"USUARIO_ID_C\"=T0.\"_id\"");
            builder.append(" LEFT JOIN SITIO T1 ON T.\"COMENTARIO_ID_C\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Comentario loadCurrentDeep(Cursor cursor, boolean lock) {
        Comentario entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Usuario usuario = loadCurrentOther(daoSession.getUsuarioDao(), cursor, offset);
        entity.setUsuario(usuario);
        offset += daoSession.getUsuarioDao().getAllColumns().length;

        Sitio sitio = loadCurrentOther(daoSession.getSitioDao(), cursor, offset);
        entity.setSitio(sitio);

        return entity;    
    }

    public Comentario loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Comentario> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Comentario> list = new ArrayList<Comentario>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Comentario> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Comentario> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
