package com.example.mrrodriguez.trianadvisor.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.example.mrrodriguez.trianadvisor.greendao.Valoracion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VALORACION".
*/
public class ValoracionDao extends AbstractDao<Valoracion, Long> {

    public static final String TABLENAME = "VALORACION";

    /**
     * Properties of entity Valoracion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property Valoracion = new Property(2, String.class, "valoracion", false, "VALORACION");
        public final static Property UpdatedAt = new Property(3, String.class, "updatedAt", false, "UPDATED_AT");
        public final static Property SitioId_v = new Property(4, Long.class, "sitioId_v", false, "SITIO_ID_V");
    };

    private DaoSession daoSession;

    private Query<Valoracion> usuario_Valoraciones_sitioQuery;

    public ValoracionDao(DaoConfig config) {
        super(config);
    }
    
    public ValoracionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VALORACION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"VALORACION\" TEXT," + // 2: valoracion
                "\"UPDATED_AT\" TEXT," + // 3: updatedAt
                "\"SITIO_ID_V\" INTEGER);"); // 4: sitioId_v
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VALORACION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Valoracion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String valoracion = entity.getValoracion();
        if (valoracion != null) {
            stmt.bindString(3, valoracion);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(4, updatedAt);
        }
 
        Long sitioId_v = entity.getSitioId_v();
        if (sitioId_v != null) {
            stmt.bindLong(5, sitioId_v);
        }
    }

    @Override
    protected void attachEntity(Valoracion entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Valoracion readEntity(Cursor cursor, int offset) {
        Valoracion entity = new Valoracion( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // valoracion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // updatedAt
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // sitioId_v
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Valoracion entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setValoracion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUpdatedAt(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSitioId_v(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Valoracion entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Valoracion entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Valoraciones_sitio" to-many relationship of Usuario. */
    public List<Valoracion> _queryUsuario_Valoraciones_sitio(Long sitioId_v) {
        synchronized (this) {
            if (usuario_Valoraciones_sitioQuery == null) {
                QueryBuilder<Valoracion> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SitioId_v.eq(null));
                usuario_Valoraciones_sitioQuery = queryBuilder.build();
            }
        }
        Query<Valoracion> query = usuario_Valoraciones_sitioQuery.forCurrentThread();
        query.setParameter(0, sitioId_v);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSitioDao().getAllColumns());
            builder.append(" FROM VALORACION T");
            builder.append(" LEFT JOIN SITIO T0 ON T.\"SITIO_ID_V\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Valoracion loadCurrentDeep(Cursor cursor, boolean lock) {
        Valoracion entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Sitio sitio = loadCurrentOther(daoSession.getSitioDao(), cursor, offset);
        entity.setSitio(sitio);

        return entity;    
    }

    public Valoracion loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Valoracion> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Valoracion> list = new ArrayList<Valoracion>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Valoracion> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Valoracion> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
